# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  communicationapigateway:
    image: communicationapigateway
    build:
      context: .
      dockerfile: CommunicationAPIGateWay/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 7000:7000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
